"""
Configuration file for MCQ Quiz Automation
Auto-generated by calibration.py
"""

# ============================================================================
# SCREEN COORDINATES - Auto-calibrated
# ============================================================================

# Quiz Screen Coordinates
QUIZ_QUESTION_AREA = {
    'x': 9,
    'y': 370,
    'width': 939,
    'height': 353
}

# Individual answer option buttons - QUESTION 1
ANSWER_OPTIONS_Q1 = {
    'A': {'x': 32, 'y': 466},
    'B': {'x': 32, 'y': 505},
    'C': {'x': 32, 'y': 547},
    'D': {'x': 31, 'y': 588},
}

# Individual answer option buttons - QUESTION 2+ (after screen shift)
ANSWER_OPTIONS_Q2 = {
    'A': {'x': 30, 'y': 435},
    'B': {'x': 32, 'y': 474},
    'C': {'x': 32, 'y': 514},
    'D': {'x': 30, 'y': 556},
}

# Next question button - QUESTION 1
NEXT_BUTTON_Q1 = {'x': 850, 'y': 1098}

# Next question button - QUESTION 2+ (after screen shift)
NEXT_BUTTON_Q2 = {'x': 814, 'y': 1071}

# Gemini Screen Coordinates
GEMINI_INPUT_FIELD = {'x': 1044, 'y': 981}
GEMINI_SEND_BUTTON = {'x': 1853, 'y': 1042}
GEMINI_RESPONSE_AREA = {
    'x': 982,
    'y': 645,
    'width': 849,
    'height': 100
}

# ============================================================================
# TIMING SETTINGS - Adjust based on your system speed and internet
# ============================================================================

DELAY_AFTER_CLICK = 0.5
DELAY_AFTER_PASTE = 1
DELAY_FOR_GEMINI_RESPONSE = 3.0
DELAY_BETWEEN_QUESTIONS = 1.0

PYAUTOGUI_PAUSE = 0.25
PYAUTOGUI_FAILSAFE = True

# ============================================================================
# AUTOMATION BEHAVIOR
# ============================================================================

QUESTION_SELECTION_METHOD = 'triple_click'
COPY_METHOD = 'ctrl_c'
USE_OCR = False
EXPECTED_ANSWER_FORMAT = 'letter'

# ============================================================================
# KEYBOARD SHORTCUTS
# ============================================================================

EMERGENCY_STOP_KEY = 'esc'
START_KEY = 'f9'

# ============================================================================
# LOGGING AND DEBUG
# ============================================================================

DEBUG_MODE = True
SAVE_SCREENSHOTS = True
SCREENSHOT_DIR = 'debug_screenshots'
LOG_FILE = 'quiz_automation.log'
